CREATE TABLE PRODUCTO(
	Codigo_barras VARCHAR(30) NOT NULL,
	Descripcion VARCHAR(50) NOT NULL,
	Tamano_porcion VARCHAR(10) NOT NULL,
	Aprobado VARCHAR(15) NOT NULL,
	Grasa INT,
	Energia INT,
	Proteina INT,
	Sodio INT,
	Carbohidratos INT,
	Hierro INT,
	Vitaminas INT,
	Calcio INT
);

CREATE TABLE RECETA(
	Nombre VARCHAR(100) NOT NULL,
	Calorias INT
);

CREATE TABLE PRODUCTOS_RECETA(
	Receta VARCHAR(100) NOT NULL,
	Producto VARCHAR(30) NOT NULL
);

CREATE TABLE TIEMPO_COMIDA(
	Nombre VARCHAR(50) NOT NULL
);

CREATE TABLE COMIDA(
	Identificador INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	Receta VARCHAR(100) NOT NULL,
	Tiempo_comida VARCHAR(50) NOT NULL
);

CREATE TABLE PLAN(
	Nombre VARCHAR(100) NOT NULL,
	Total_calorias INT,
	Comida INT NOT NULL
);

CREATE TABLE NUTRICIONISTA(
	Cedula INT NOT NULL,
	Foto TEXT,
	Nombre VARCHAR(50) NOT NULL,
	Apellido1 VARCHAR(50) NOT NULL,
	Apellido2 VARCHAR(50),
	Correo VARCHAR(100) NOT NULL,
	Fecha_nacimiento DATE NOT NULL,
	Edad INT NOT NULL,
	Tipo_cobro VARCHAR(50) NOT NULL,
	Tipo_pago VARCHAR(50) NOT NULL,
	Codigo VARCHAR(50) NOT NULL,
	Tarjeta_credito VARCHAR(30) NOT NULL,
	Contrasena VARCHAR(100) NOT NULL,
	Direccion VARCHAR(100) NOT NULL,
	IMC INT NOT NULL,
	Peso INT NOT NULL
);

CREATE TABLE PLANES_NUTRICIONISTA(
	Nutricionista INT NOT NULL,
	Plan VARCHAR(100) NOT NULL
);

CREATE TABLE CLIENTE(
	Correo VARCHAR(100) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Apellido1 VARCHAR(50) NOT NULL,
	Apellido2 VARCHAR(50),
	Contrasena VARCHAR(100) NOT NULL,
	Pais VARCHAR(25) NOT NULL,
	Fecha_registro DATE NOT NULL,
	Fecha_nacimiento DATE NOT NULL,
	Edad INT,
	IMC INT,
	PESO INT
);
	
CREATE TABLE PLANES_CLIENTE(
	Cliente VARCHAR(100) NOT NULL,
	Plan VARCHAR(100) NOT NULL,
	Fecha_inicio DATE NOT NULL,
	Fecha_final DATE NOT NULL
);

CREATE TABLE CONSUMO(
	Identificador INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	Cliente VARCHAR(50) NOT NULL,
	Receta VARCHAR(100) NOT NULL
);

CREATE TABLE MEDIDA(
	Identificador INT GENERATED ALWAYS AS IDENTITY NOT NULL,
	Fecha DATE,
	Cintura INT,
	Grasa INT,
	Musculo INT,
	Cadera INT,
	Cuello INT
);

CREATE TABLE MEDIDAS_CLIENTE(
	Cliente VARCHAR(100) NOT NULL,
	Medida INT NOT NULL
);

CREATE TABLE ADMINISTRADOR(
	Correo VARCHAR(100) NOT NULL,
	Contrasena VARCHAR(100) NOT NULL
);


-- Primary keys
ALTER TABLE PRODUCTO
	ADD PRIMARY KEY (Codigo_barras);
	
ALTER TABLE RECETA
	ADD PRIMARY KEY (Nombre);

ALTER TABLE PRODUCTOS_RECETA
	ADD PRIMARY KEY (Producto, Receta);
	
ALTER TABLE TIEMPO_COMIDA
	ADD PRIMARY KEY (Nombre);
	
ALTER TABLE COMIDA
	ADD PRIMARY KEY (Identificador);
	
ALTER TABLE PLAN
	ADD PRIMARY KEY (Nombre);
	
ALTER TABLE NUTRICIONISTA
	ADD PRIMARY KEY (Cedula);
	
ALTER TABLE CLIENTE
	ADD PRIMARY KEY (Correo);
	
ALTER TABLE PLANES_CLIENTE
	ADD PRIMARY KEY (Cliente, plan);

ALTER TABLE CONSUMO
	ADD PRIMARY KEY (Identificador);
	
ALTER TABLE MEDIDA
	ADD PRIMARY KEY (Identificador);

ALTER TABLE MEDIDAS_CLIENTE
	ADD PRIMARY KEY (Cliente, Medida);
	
ALTER TABLE ADMINISTRADOR
	ADD PRIMARY KEY (Correo);


-- Foreign keys
ALTER TABLE PRODUCTOS_RECETA
	ADD FOREIGN KEY (Producto) REFERENCES PRODUCTO(Codigo_barras),
	ADD FOREIGN KEY (Receta) REFERENCES RECETA(Nombre);

ALTER TABLE COMIDA
	ADD FOREIGN KEY (Receta) REFERENCES RECETA(Nombre),
	ADD FOREIGN KEY (Tiempo_comida) REFERENCES TIEMPO_COMIDA(Nombre);

ALTER TABLE PLAN
	ADD FOREIGN KEY (Comida) REFERENCES COMIDA(Identificador);
	
ALTER TABLE PLANES_NUTRICIONISTA
	ADD FOREIGN KEY (Nutricionista) REFERENCES NUTRICIONISTA(Cedula),
	ADD FOREIGN KEY (Plan) REFERENCES PLAN(Nombre);
	
ALTER TABLE PLANES_CLIENTE
	ADD FOREIGN KEY (Cliente) REFERENCES CLIENTE(Correo),
	ADD FOREIGN KEY (Plan) REFERENCES PLAN(Nombre);
	
ALTER TABLE CONSUMO
	ADD FOREIGN KEY (Cliente) REFERENCES CLIENTE(Correo),
	ADD FOREIGN KEY (Receta) REFERENCES RECETA(Nombre);

ALTER TABLE MEDIDAS_CLIENTE
	ADD FOREIGN KEY (Cliente) REFERENCES CLIENTE(Correo),
	ADD FOREIGN KEY (Medida) REFERENCES MEDIDA(Identificador);
	
	
	
-- Inserts
INSERT INTO TIEMPO_COMIDA VALUES('Desayuno');
INSERT INTO TIEMPO_COMIDA VALUES('Merienda mañana');
INSERT INTO TIEMPO_COMIDA VALUES('Almuerzo');
INSERT INTO TIEMPO_COMIDA VALUES('Merienda tarde');
INSERT INTO TIEMPO_COMIDA VALUES('Cena');

SELECT * FROM TIEMPO_COMIDA